  hosts: appservers
  become: yes

- name: Java Version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/[^0-9._]//g'
  register: java_version

- name: Java Build
  shell: java -version 2>&1 | grep "Server VM .build"
  register: java_build
