---
- name: My Super Playbook for Variables Lesson
  hosts: all
  become: yes


  vars:
    message1: Privet
    message2: World
    secret: JLH234JL

  tasks:

  - name: Print Secret variables
    debug:
      var: secret


  - set_fact: full_message="{{ message1 }} {{ message2 }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution
