---
# file: tasks/install.yml
# Top-level installer for Oracle JDK.
#


- name: fetch .rpm or .tar.gz files from Oracle site
  include: fetch.yml
  when: java_download_from_oracle

- block:

    - name: copy RPM from local
      copy:
        src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.rpm"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
      when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper"

    - name: copy tarball from local
      copy:
        src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.tar.gz"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
      when: ansible_pkg_mgr != "yum" and ansible_pkg_mgr != "zypper"

  when: not java_download_from_oracle



- name: delegate to RPM installation process
  include: use-rpm.yml
  when: (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper") and ansible_os_family != 'Darwin'

- name: delegate to raw tarball installation process
  include: use-tarball.yml
  when: ansible_pkg_mgr != "yum" and ansible_pkg_mgr != "zypper" and ansible_os_family != 'Darwin'

- name: delegate to Mac OS X dmg installation
  include: use-dmg.yml
  when: ansible_os_family == 'Darwin'

- block:

    - name: make sure /etc/profile.d exists
      file: path=/etc/profile.d  state=directory

    - name: export JAVA_HOME
      template:
        src:  ../templates/java_home.sh.j2
        dest: /etc/profile.d/java_home.sh
        mode: "a+x"

  when: java_set_javahome






- name: remove temporary downloaded files, if requested
  file: path={{ item }} state=absent
  with_items:
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"
    - "{{ java_download_path }}/check-tarball-installed.sh"
  ignore_errors: true
  when: java_remove_download
