---
# tasks file for jenkins
- name: Creating jenkins Group
  group:
    name: "{{ user_group }}"
    state: present

- name: Creating the user jenkins
  user:     
    name: "{{ name_user }}"
    group: "{{ user_group }}"
    state: present

- name: Create Jenkins_home folder
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ name_user }}"
    group: "{{ user_group }}"
    mode: 0755

- name: Create Jenkins bin folder
  file:
    path: "{{ jenkins_bin }}"
    state: directory
    owner: "{{ name_user }}"
    group: "{{ user_group }}"
    mode: 0755

- name: Download Jenkins .war
  get_url: 
    url: "{{ jenkins_download_url }}" 
    dest: "{{ jenkins_bin }}"

- name: Create Jenkins unit
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service

- name: Jenkins Service Running and Enabled
  service: 
    name: jenkins
    state: started
    enabled: yes
